# STAGE01 - Build application and its dependencies
FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /app
#COPY *.csproj ./  Inside api core
# COPY *.csproj ./ Inside api core 
# COPY . ./   Inside api core
COPY ./WeatherAppApi/*.csproj ./
COPY ./WeatherAppApi ./
RUN dotnet restore 

# STAGE02 - Publish the application
FROM build-env AS publish
RUN dotnet publish -c Release -o /app

# STAGE03 - Create the final image
FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app
LABEL Author="Akhil S"
LABEL Maintainer="weatherman"
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WeatherAppApi.dll", "--server.urls", "http://*:5000"]