version: '2.1'
services:  
 redis_image:
  image: redis
  container_name: cachev1  
  networks:
      - production-network
  ports:
   - "6379:6379" 
 web:              
  build:
   context: .
   dockerfile: DockerFile
  links:
   - redis_image
  container_name: DotNetCore-Service
  networks:
      - production-network
  restart: always
  ports:
   - "5000:80"       
  depends_on:
   - redis_image
networks:
  production-network:
    driver: bridge
  

  